// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package models

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/maximmihin/as25/internal/dal/types"
)

const create = `-- name: Create :exec
INsert into pvz (id, created_at, located_at)
VALUES ($1, $2, $3)
RETURNING id, created_at, located_at
`

type CreateParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	LocatedAt types.FtCity
}

// todo why am i need return? if i dictate id and creation time?
func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create, arg.ID, arg.CreatedAt, arg.LocatedAt)
	return err
}
